# Generated by Django 6.0.5 on 2026-10-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('path', models.CharField(db_index=True, max_length=300)),
                ('section', models.CharField(db_index=True, max_length=20)),
                ('visitor', models.CharField(db_index=True, max_length=16)),
                ('source', models.CharField(choices=[('direct', '직접 방문'), ('search', '검색'), ('kakao', '카카오톡'), ('github', 'GitHub'), ('social', 'SNS·메신저'), ('internal', '사이트 안 이동'), ('other', '다른 사이트')], db_index=True, max_length=10)),
                ('referrer_host', models.CharField(blank=True, max_length=120)),
                ('device', models.CharField(choices=[('desktop', 'PC'), ('mobile', '모바일'), ('tablet', '태블릿')], max_length=10)),
                ('is_member', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['day', 'section'], name='analytics_p_day_41c551_idx')],
            },
        ),
    ]
