# Generated by Django 6.0.5 on 2026-05-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='current_status',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='profile_badge',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
