# Generated by Django 6.0.5 on 2026-05-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_remove_basicinfo_current_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='location',
        ),
    ]
