# Generated by Django 6.0.5 on 2026-05-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_remove_basicinfo_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('address', 'Address')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('value', models.TextField()),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
