# Generated by Django 6.0.5 on 2026-05-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('velog', 'Velog'), ('tistory', 'Tistory'), ('linkedin', 'LinkedIn'), ('notion', 'Notion'), ('scholar', 'Google Scholar'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('x', 'X'), ('website', 'Website'), ('other', 'Other')], max_length=30)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField()),
                ('is_visible', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
