# Generated by Django 6.0.5 on 2026-05-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='platform',
            field=models.CharField(choices=[('github', 'GitHub'), ('velog', 'Velog'), ('tistory', 'Tistory'), ('linkedin', 'LinkedIn'), ('notion', 'Notion'), ('scholar', 'Google Scholar'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('x', 'X'), ('website', 'Website'), ('other', 'Other')], max_length=30),
        ),
    ]
