# Generated by Django 6.0.5 on 2026-05-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0006_alter_link_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(choices=[("education", "Education"), ("internship", "Internship"), ("research", "Research"), ("leadership", "Leadership"), ("teaching", "Teaching / Assistant")], max_length=30)),
                ("title", models.CharField(max_length=200)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("is_visible", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "-start_date", "id"],
            },
        ),
    ]
