# Generated by Django 6.0.5 on 2026-05-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0012_teaching_start_end_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('community', 'Community'), ('seminar', 'Seminar'), ('volunteer', 'Volunteer'), ('contest', 'Contest'), ('other', 'Other')], default='community', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-start_date', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('none', '해당없음'), ('bachelor', '학부'), ('master', '석사'), ('phd', '박사')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='role',
            field=models.CharField(choices=[('ta', 'TA / Assistant'), ('instructor', '강사'), ('professor', '멘토'), ('curriculum', '교재개발')], default='ta', max_length=20),
        ),
    ]
