# Generated by Django 6.0.5 on 2026-05-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0013_activity_alter_education_degree_alter_teaching_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('external_program', 'External Program'), ('community', 'Community'), ('seminar', 'Seminar'), ('volunteer', 'Volunteer'), ('contest', 'Contest'), ('other', 'Other')], default='external_program', max_length=20),
        ),
    ]
