# Generated by Django 6.0.5 on 2026-05-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0020_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_type', models.CharField(choices=[('international', '국제지/국제학회'), ('domestic', '국내지/국내학회')], default='international', max_length=20)),
                ('publication_kind', models.CharField(choices=[('journal', '저널'), ('conference', '학술지')], default='journal', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('authors', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, max_length=255, null=True, upload_to='publication/')),
                ('preview_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='publication/previews/')),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-date', 'id'],
            },
        ),
    ]
