# Generated by Django 6.0.5 on 2026-05-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0023_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='certification/'),
        ),
        migrations.AddField(
            model_name='certification',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='certification/previews/'),
        ),
    ]
