# Generated by Django 6.0.5 on 2026-05-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0024_certification_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='project/')),
                ('github_url', models.URLField(blank=True)),
                ('deploy_url', models.URLField(blank=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('team_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('contribution', models.CharField(blank=True, max_length=100)),
                ('tech_stack', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('role', models.TextField(blank=True)),
                ('key_points', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('results', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='project/attachments/')),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-period_start', 'id'],
            },
        ),
    ]
