# Generated by Django 6.0.5 on 2026-05-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0025_add_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detail_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='project/'),
        ),
        migrations.AddField(
            model_name='project',
            name='detail_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='project/'),
        ),
        migrations.AddField(
            model_name='project',
            name='detail_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='project/'),
        ),
    ]
