# Generated by Django 6.0.5 on 2026-05-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0026_project_more_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('research', '연구'), ('personal', '개인'), ('team', '팀 프로젝트')], default='team', max_length=20),
        ),
    ]
