# Generated by Django 6.0.5 on 2026-05-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0027_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', '진행중'), ('completed', '완료'), ('on_hold', '보류')], default='in_progress', max_length=20),
        ),
    ]
