# Generated by Django 6.0.5 on 2026-05-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0028_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_attachment_public',
            field=models.BooleanField(default=True, help_text='파일 공개 여부'),
        ),
    ]
