# Generated by Django 6.0.5 on 2026-05-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0029_activity_is_attachment_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('language_framework', 'Language & Framework'), ('devops_infra', 'DevOps/Infra'), ('test_security', 'Test & Security'), ('platform', 'Platform'), ('other', 'Other')], default='language_framework', max_length=30)),
                ('note', models.CharField(blank=True, max_length=150)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
