# Generated by Django 6.0.5 on 2026-10-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0031_sitesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
