# Generated by Django 6.0.5 on 2026-10-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprequest',
            name='privacy_agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='개인정보 수집·이용 동의 시각'),
        ),
    ]
