# Generated by Django 6.0.5 on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_comment_author_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="access_password",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "전체공개"),
                    ("private", "비공개"),
                    ("protected", "일부공개(비밀번호)"),
                ],
                db_index=True,
                default="public",
                max_length=20,
            ),
        ),
    ]
