# Generated by Django 6.0.5 on 2026-10-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_guestbookentry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_agent',
            field=models.CharField(blank=True, max_length=300, verbose_name='작성 브라우저'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='작성 IP'),
        ),
        migrations.AddField(
            model_name='guestbookentry',
            name='author_agent',
            field=models.CharField(blank=True, max_length=300, verbose_name='작성 브라우저'),
        ),
        migrations.AddField(
            model_name='guestbookentry',
            name='author_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='작성 IP'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_agent',
            field=models.CharField(blank=True, max_length=300, verbose_name='작성 브라우저'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='작성 IP'),
        ),
    ]
