from .profile import (
    index,
    profile,
    profile_basic,
    profile_contact,
    profile_contact_update,
    profile_contact_delete,
    profile_contact_toggle_visibility,
    profile_links,
    profile_link_update,
    profile_link_delete,
    profile_link_toggle_visibility,
    profile_link_toggle_primary,
    profile_resume,
)
from .career import (
    career,
    education_create,
    education_update,
    education_delete,
    education_toggle_visibility,
    education_reorder,
    internship_create,
    internship_update,
    internship_delete,
    internship_toggle_visibility,
    internship_reorder,
    research_create,
    research_update,
    research_delete,
    research_toggle_visibility,
    research_reorder,
    leadership_create,
    leadership_update,
    leadership_delete,
    leadership_toggle_visibility,
    leadership_reorder,
    teaching_create,
    teaching_update,
    teaching_delete,
    teaching_toggle_visibility,
    teaching_reorder,
)
from .activity import (
    activity,
    activity_create,
    activity_update,
    activity_delete,
    activity_toggle_visibility,
    activity_reorder,
)
from .award import (
    award,
    award_create,
    award_update,
    award_delete,
    award_toggle_visibility,
    award_reorder,
)
from .publication import (
    publication,
    publication_create,
    publication_update,
    publication_delete,
    publication_toggle_visibility,
    publication_reorder,
)
from .certification import (
    certification,
    certification_create,
    certification_update,
    certification_delete,
    certification_toggle_visibility,
    certification_reorder,
)
from .project import (
    project,
    project_create,
    project_update,
    project_delete,
    project_toggle_visibility,
    project_reorder,
)
from .skill import (
    skill,
    skill_create,
    skill_update,
    skill_delete,
    skill_toggle_visibility,
)
from .posts import (
    posts,
    post_visibility_update,
    post_delete,
)
