# Generated by Django 6.0.5 on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="tags",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="photo",
            name="taken_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name="photo",
            options={"ordering": ["-taken_at", "-created_at", "-id"]},
        ),
    ]
