# Generated by Django 6.0.5 on 2026-10-09 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('boot_id', models.CharField(max_length=64)),
                ('rx_bytes', models.BigIntegerField()),
                ('tx_bytes', models.BigIntegerField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UptimeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('kind', models.CharField(choices=[('http', '웹 주소 (HTTP)'), ('tcp', '포트 (TCP)')], default='http', max_length=10)),
                ('target', models.CharField(max_length=300)),
                ('interval_min', models.PositiveSmallIntegerField(default=5)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unknown', '확인 전'), ('up', '정상'), ('down', '장애')], default='unknown', max_length=10)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_change_at', models.DateTimeField(blank=True, null=True)),
                ('last_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('fail_streak', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UptimeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ok', models.BooleanField()),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitor.uptimetarget')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
