# Generated by Django 6.0.5 on 2026-10-09 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('2048', '2048'), ('typing-ko', '타자 · 한글'), ('typing-en', '타자 · 영어'), ('typing-code', '타자 · 코딩')], max_length=20)),
                ('score', models.IntegerField()),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'created_at'],
                'indexes': [models.Index(fields=['board', '-score'], name='games_score_board_b46226_idx')],
            },
        ),
    ]
