"""Tool 허브에 보여줄 도구 목록.

새 도구를 추가할 때는
1. tools/urls.py 에 페이지 URL 추가
2. templates/tools/ 에 템플릿 추가
3. 아래 TOOLS 에 한 줄 추가
하면 허브(/tools/)에 카드가 생긴다.

"category" 로 허브의 칸이 나뉜다 (CATEGORIES 의 key, 도구가 하나도 없는 칸은 보이지 않음).

"access" 는 누가 쓸 수 있는지:
- "public": 누구나
- "member": 회원 전용 (비로그인에게도 보이지만 🔒 표시, 누르면 로그인 화면으로)
- "admin":  관리자 전용 (관리자에게만 보이고, 분류와 상관없이 맨 아래 "관리자 전용" 칸에 모임)
실제 접근 제한은 각 뷰에서 따로 건다.
"""

CATEGORIES = [
	("docs", "📝", "문서 · 공부", "자소서·과제·PDF·학점, 공부할 때 쓰는 도구"),
	("share", "🔗", "공유 · 전송", "파일·글·화면을 다른 사람이나 내 다른 기기로"),
	("network", "🌐", "네트워크", "내 인터넷과 서버 상태 확인, 네트워크 계산기"),
	("dev", "🛠", "개발 · 보안", "데이터 변환, 정규식, 해시와 키 만들기"),
]

TOOLS = [
	{
		"slug": "charcount",
		"url_name": "tools:charcount",
		"icon": "✍️",
		"title": "글자 수 세기",
		"description": "자소서·과제 글자 수를 공백 포함·제외, 바이트, 원고지 매수로 세고, 목표 글자 수까지 얼마 남았는지·많이 쓴 단어·너무 긴 문장을 알려줘요.",
		"tags": ["자소서", "글쓰기"],
		"category": "docs",
		"access": "public",
	},
	{
		"slug": "diff",
		"url_name": "tools:textdiff",
		"icon": "🔀",
		"title": "글 비교",
		"description": "두 글에서 바뀐 부분을 색으로 보여줘요. 줄·단어·글자 단위, 나란히 보기, 공백 무시. 자소서 수정본·계약서 비교에 좋아요.",
		"tags": ["문서", "비교"],
		"category": "docs",
		"access": "public",
	},
	{
		"slug": "pdf",
		"url_name": "tools:pdf",
		"icon": "📄",
		"title": "PDF 도구",
		"description": "PDF 합치기·나누기, 페이지 빼기·돌리기·순서 바꾸기, 사진 여러 장을 PDF 하나로. 파일이 서버로 가지 않고 브라우저 안에서만 처리돼요.",
		"tags": ["문서", "PDF"],
		"category": "docs",
		"access": "public",
	},
	{
		"slug": "image",
		"url_name": "tools:image",
		"icon": "🖼",
		"title": "이미지 도구",
		"description": "사진 용량 줄이기(“5MB 이하로”), 크기·형식 바꾸기(HEIC → JPG, PNG ↔ WebP), 자르기·돌리기, 위치정보 지우기. 여러 장을 한꺼번에 ZIP 으로 받아요. 브라우저 안에서만 처리돼요.",
		"tags": ["사진", "변환"],
		"category": "docs",
		"access": "public",
	},
	{
		"slug": "ocr",
		"url_name": "tools:ocr",
		"icon": "📷",
		"title": "사진 글자 추출",
		"description": "사진·캡처·문서 속 글자를 뽑아 바로 복사해요. 기본은 무료로 읽고, 손글씨·칠판·표는 ✨AI 로 다시 읽으면 훨씬 정확해요(회원). 여러 장, ⌘V 붙여넣기.",
		"tags": ["OCR", "AI"],
		"category": "docs",
		"access": "public",  # 무료 읽기는 누구나, AI 읽기는 회원
	},
	{
		"slug": "gpa",
		"url_name": "tools:gpa",
		"icon": "🎓",
		"title": "학점 계산기",
		"description": "과목별·학기별 평점과 전공 평점, 4.5 ↔ 4.3 ↔ 100점 환산, 목표 학점까지 앞으로 몇 점이 필요한지 계산해요. 성적은 이 브라우저에만 저장돼요.",
		"tags": ["대학생", "계산기"],
		"category": "docs",
		"access": "public",
	},
	{
		"slug": "stream",
		"url_name": "tools:stream",
		"icon": "📁",
		"title": "데이터 전송",
		"description": "방을 열고 링크를 나눠 주면 브라우저끼리 파일을 바로 주고받아요. 받는 사람이 없으면 맡겨두기, 프로그램 실시간 스트림·GNU Radio(ZMQ) IQ 중계도 지원합니다.",
		"tags": ["파일", "스트리밍"],
		"category": "share",
		"access": "member",  # 방 만들기는 회원(한도 있음), 받는 쪽은 링크만 있으면 누구나 — tools/permissions.py
	},
	{
		"slug": "meet",
		"url_name": "tools:meet",
		"icon": "📅",
		"title": "팀플 일정 맞추기",
		"description": "날짜와 시간대를 정해 링크를 돌리면, 각자 되는 시간을 드래그로 칠해요. 겹치는 시간이 진하게 보이고 '모두 되는 시간'을 바로 찾아줘요. 참여는 로그인 없이.",
		"tags": ["팀플", "약속"],
		"category": "share",
		"access": "member",  # 만들기는 회원, 링크로 참여는 누구나
	},
	{
		"slug": "clipboard",
		"url_name": "tools:clipboard",
		"icon": "📋",
		"title": "내 클립보드",
		"description": "로그인한 계정에 텍스트·이미지·파일을 붙여넣어 두고, 휴대폰·노트북 등 다른 기기에서 바로 복사하거나 내려받습니다.",
		"tags": ["기기 간 공유"],
		"category": "share",
		"access": "member",
	},
	{
		"slug": "shortlink",
		"url_name": "tools:shortlink",
		"icon": "🔗",
		"title": "단축 URL",
		"description": "긴 주소를 smjgallery.kr/s/abc123 처럼 짧게 줄이고, 몇 번 열렸는지 확인해요. 유효 기간도 정할 수 있어요.",
		"tags": ["링크", "공유"],
		"category": "share",
		"access": "member",
	},
	{
		"slug": "secret",
		"url_name": "tools:secret",
		"icon": "🤫",
		"title": "1회용 비밀 메모",
		"description": "비밀번호·키 같은 걸 한 번 열면 사라지는 링크로 전달해요. 브라우저에서 암호화해서 서버는 내용을 알 수 없어요.",
		"tags": ["보안", "공유"],
		"category": "share",
		"access": "member",
	},
	{
		"slug": "qrcode",
		"url_name": "tools:qrcode",
		"icon": "▦",
		"title": "QR 코드 만들기",
		"description": "주소·글·Wi-Fi·연락처·문자·메일을 QR 코드로 만들어요. 색·모양·가운데 로고를 바꾸고 PNG·SVG 로 저장, 사진 속 QR 읽기도 돼요.",
		"tags": ["생성기", "공유"],
		"category": "share",
		"access": "public",
	},
	{
		"slug": "live",
		"url_name": "tools:live",
		"icon": "📺",
		"title": "라이브 방송",
		"description": "화면·웹캠·마이크로 실시간 방송하고, 링크 받은 사람은 로그인 없이 보며 채팅해요. 직접 연결이 막힌 네트워크는 서버가 중계해요.",
		"tags": ["방송", "WebRTC"],
		"category": "share",
		"access": "member",
	},
	{
		"slug": "myip",
		"url_name": "tools:myip",
		"icon": "🔍",
		"title": "내 IP · 접속 정보",
		"description": "이 서버가 본 내 공인 IP, IPv4/IPv6, 호스트 이름, 브라우저·OS·화면 정보를 보여주고, 원하면 IP 대역의 통신사·국가도 찾아 줍니다.",
		"tags": ["네트워크", "IP"],
		"category": "network",
		"access": "public",
	},
	{
		"slug": "speedtest",
		"url_name": "tools:speedtest",
		"icon": "⚡",
		"title": "인터넷 속도 측정",
		"description": "지금 내 인터넷으로 이 서버와 실제 데이터를 주고받아 다운로드·업로드 속도와 지연(ping)을 실시간 그래프로 측정합니다.",
		"tags": ["네트워크", "실시간 측정"],
		"category": "network",
		"access": "member",
	},
	{
		"slug": "netcheck",
		"url_name": "tools:netcheck",
		"icon": "📡",
		"title": "포트 · 핑 · DNS 체크",
		"description": "이 서버에서 내 서버로 포트가 열려 있는지, ping 응답 시간, 경로(traceroute), DNS 레코드(A·MX·TXT 등)를 확인합니다.",
		"tags": ["네트워크", "진단"],
		"category": "network",
		"access": "member",
	},
	{
		"slug": "subnet",
		"url_name": "tools:subnet",
		"icon": "⌗",
		"title": "IPv4 서브넷 계산기",
		"description": "IP/CIDR 이나 서브넷 마스크를 넣으면 네트워크·브로드캐스트·호스트 범위를 계산하고, 2진수로 보여주고, 더 작은 서브넷으로 나눠 줍니다.",
		"tags": ["네트워크", "계산기"],
		"category": "network",
		"access": "public",
	},
	{
		"slug": "duplex",
		"url_name": "tools:duplex",
		"icon": "⇄",
		"title": "Full / Half Duplex 처리량 비교",
		"description": "회선 속도·프레임 크기·방향 전환 시간을 넣으면 전이중과 반이중의 실제 처리량과 전송 시간을 비교해 줍니다.",
		"tags": ["네트워크", "계산기"],
		"category": "network",
		"access": "public",
	},
	{
		"slug": "json",
		"url_name": "tools:json",
		"icon": "{ }",
		"title": "JSON 정리",
		"description": "JSON 을 보기 좋게 정리하거나 한 줄로 줄이고, 오류 위치를 짚어 주고, 접고 펼치는 트리로 보여줘요. 키 정렬·CSV 변환도 돼요.",
		"tags": ["개발", "변환"],
		"category": "dev",
		"access": "public",
	},
	{
		"slug": "regex",
		"url_name": "tools:regex",
		"icon": ".*",
		"title": "정규식 테스트",
		"description": "정규식을 입력하면 맞는 부분을 바로 칠해 주고, 그룹·치환 결과와 패턴 설명을 보여줘요. 자주 쓰는 패턴 모음도 있어요.",
		"tags": ["개발", "텍스트"],
		"category": "dev",
		"access": "public",
	},
	{
		"slug": "encode",
		"url_name": "tools:encode",
		"icon": "🧮",
		"title": "인코딩 · 해시 도구",
		"description": "Base64·URL·Hex·HTML 변환, MD5·SHA 해시와 HMAC, 파일 해시, JWT 내용 보기. 모두 브라우저 안에서만 계산해요.",
		"tags": ["보안", "변환"],
		"category": "dev",
		"access": "public",
	},
	{
		"slug": "keygen",
		"url_name": "tools:keygen",
		"icon": "🔑",
		"title": "암호화 키 생성기",
		"description": "길이·문자 종류·형식(Hex·Base64·UUID·PIN·API 키)을 골라 안전한 키와 비밀번호를 만들고, RSA·ECDSA 키 쌍도 PEM 으로 생성합니다. 모두 브라우저 안에서만 만들어져요.",
		"tags": ["보안", "생성기"],
		"category": "dev",
		"access": "public",
	},
]
