from django.urls import path

from . import clipboard_views, link_views, myip, netcheck, share_views, speedtest, views

app_name = "tools"

urlpatterns = [
    path("", views.index, name="index"),
    path("duplex/", views.duplex, name="duplex"),
    path("subnet/", views.subnet, name="subnet"),
    path("speedtest/", views.speedtest, name="speedtest"),
    path("keygen/", views.keygen, name="keygen"),
    path("myip/", myip.myip, name="myip"),
    path("myip/lookup/", myip.myip_lookup, name="myip_lookup"),
    path("encode/", views.encode, name="encode"),
    path("netcheck/", netcheck.netcheck, name="netcheck"),
    path("netcheck/run/", netcheck.netcheck_run, name="netcheck_run"),
    path("shortlink/", link_views.shortlink, name="shortlink"),
    path("shortlink/<str:code>/delete/", link_views.shortlink_delete, name="shortlink_delete"),
    path("secret/", link_views.secret, name="secret"),
    path("secret/new/", link_views.secret_create, name="secret_create"),
    path("secret/<str:note_id>/", link_views.secret_view, name="secret_view"),
    path("secret/<str:note_id>/reveal/", link_views.secret_reveal, name="secret_reveal"),
    path("secret/<str:note_id>/delete/", link_views.secret_delete, name="secret_delete"),
    path("speedtest/ping/", speedtest.ping, name="speedtest_ping"),
    path("speedtest/download/", speedtest.download, name="speedtest_download"),
    path("speedtest/upload/", speedtest.upload, name="speedtest_upload"),
    path("clipboard/", clipboard_views.clipboard_page, name="clipboard"),
    path("clipboard/api/items/", clipboard_views.clipboard_list, name="clipboard_list"),
    path("clipboard/api/items/add/", clipboard_views.clipboard_add, name="clipboard_add"),
    path("clipboard/api/items/clear/", clipboard_views.clipboard_clear, name="clipboard_clear"),
    path("clipboard/api/items/<int:item_id>/pin/", clipboard_views.clipboard_pin, name="clipboard_pin"),
    path("clipboard/api/items/<int:item_id>/delete/", clipboard_views.clipboard_delete, name="clipboard_delete"),
    path("clipboard/<int:item_id>/file/", clipboard_views.clipboard_file, name="clipboard_file"),
    path("share/", share_views.share_page, name="share"),
    path("share/new/", share_views.share_create, name="share_create"),
    path("share/<str:token>/", share_views.share_download_page, name="share_download_page"),
    path("share/<str:token>/download/", share_views.share_download, name="share_download"),
    path("share/<str:token>/chunk/", share_views.share_chunk, name="share_chunk"),
    path("share/<str:token>/complete/", share_views.share_complete, name="share_complete"),
    path("share/<str:token>/delete/", share_views.share_delete, name="share_delete"),
    path("stream/", views.stream_list, name="stream"),
    path("stream/<str:room_id>/", views.stream_room, name="stream_room"),
    path("stream/<str:room_id>/close/", views.stream_close, name="stream_close"),
    path("stream/<str:room_id>/join/", views.stream_join, name="stream_join"),
]
