# Generated by Django 6.0.5 on 2026-10-08 00:28

import django.db.models.deletion
import tools.models
import tools.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', '텍스트'), ('image', '이미지'), ('file', '파일')], max_length=10)),
                ('text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, storage=tools.storage.private_storage, upload_to=tools.models.clip_upload_to)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('mime', models.CharField(blank=True, max_length=120)),
                ('size', models.BigIntegerField(default=0)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned', '-created_at', '-id'],
            },
        ),
    ]
