# Generated by Django 6.0.5 on 2026-10-08 00:36

import django.db.models.deletion
import tools.models
import tools.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=tools.models._share_token, max_length=64, unique=True)),
                ('file', models.FileField(blank=True, storage=tools.storage.private_storage, upload_to=tools.models.shared_upload_to)),
                ('name', models.CharField(max_length=255)),
                ('mime', models.CharField(blank=True, max_length=120)),
                ('size', models.BigIntegerField()),
                ('received', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('completed', models.BooleanField(default=False)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
