# Generated by Django 6.0.5 on 2026-10-09 07:58

import django.db.models.deletion
import tools.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_secretnote_shortlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_id', models.CharField(default=tools.models._meet_id, max_length=24, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('dates', models.JSONField()),
                ('start_min', models.PositiveSmallIntegerField()),
                ('end_min', models.PositiveSmallIntegerField()),
                ('slot_min', models.PositiveSmallIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('key_hash', models.CharField(max_length=64)),
                ('pin_hash', models.CharField(blank=True, max_length=128)),
                ('slots', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tools.meeting')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('meeting', 'name'), name='uniq_meeting_response_name')],
            },
        ),
    ]
