# Generated by Django 6.0.5 on 2026-10-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_aiusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusage',
            name='feature',
            field=models.CharField(choices=[('qr', 'QR 스타일 추천'), ('regex', '정규식 만들기'), ('diff', '글 비교 요약'), ('netcheck', '네트워크 결과 풀이'), ('ocr', '사진 글자 추출')], max_length=20),
        ),
    ]
