# Generated by Django 6.0.5 on 2026-10-09 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_rename_friends_group_to_vip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('todo', '읽을 것'), ('reading', '읽는 중'), ('done', '다 읽음')], default='todo', max_length=10)),
                ('starred', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starred', '-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='unique_saved_paper')],
            },
        ),
    ]
