# Generated by Django 6.0.5 on 2026-10-09 17:47

import django.db.models.deletion
import tools.models
import tools.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_aiusage_paper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusage',
            name='feature',
            field=models.CharField(choices=[('qr', 'QR 스타일 추천'), ('regex', '정규식 만들기'), ('diff', '글 비교 요약'), ('netcheck', '네트워크 결과 풀이'), ('ocr', '사진 글자 추출'), ('paper', '논문 정리'), ('stdlib', '표준 서재 질문')], max_length=20),
        ),
        migrations.CreateModel(
            name='StdDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(storage=tools.storage.private_storage, upload_to=tools.models.stddoc_upload_to)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('chunks', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', '나누는 중'), ('ready', '준비됨'), ('error', '실패')], default='processing', max_length=12)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StdChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('kind', models.CharField(default='clause', max_length=8)),
                ('clause', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('page', models.PositiveIntegerField(default=1)),
                ('text', models.TextField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='tools.stddoc')),
            ],
            options={
                'ordering': ['doc_id', 'order'],
                'indexes': [models.Index(fields=['doc', 'clause'], name='tools_stdch_doc_id_a6d33f_idx')],
            },
        ),
    ]
