# Generated by Django 6.0.5 on 2026-10-10 14:02

import django.db.models.deletion
import tools.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_aiusage_github'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paste_id', models.CharField(default=tools.models._paste_id, max_length=24, unique=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(default='auto', max_length=30)),
                ('content', models.TextField()),
                ('size', models.PositiveIntegerField(default=0)),
                ('forked_from', models.CharField(blank=True, max_length=24)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
