# Generated by Django 6.0.5 on 2026-10-10 15:18

import django.db.models.deletion
import tools.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_paste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HookBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_id', models.CharField(default=tools.models._hook_id, max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=60)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('response_type', models.CharField(choices=[('json', 'JSON'), ('text', '글')], default='json', max_length=10)),
                ('response_body', models.TextField(blank=True, default='{"ok": true}')),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hook_bins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=12)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('query', models.TextField(blank=True)),
                ('headers', models.JSONField(default=list)),
                ('body', models.TextField(blank=True)),
                ('body_base64', models.BooleanField(default=False)),
                ('body_size', models.PositiveIntegerField(default=0)),
                ('truncated', models.BooleanField(default=False)),
                ('content_type', models.CharField(blank=True, max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='tools.hookbin')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
