# Generated by Django 6.0.5 on 2026-10-10 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_webhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True)),
                ('kind', models.CharField(default='TS', max_length=2)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('version', models.CharField(blank=True, max_length=16)),
                ('release', models.CharField(blank=True, max_length=4)),
                ('zip_url', models.URLField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', '기다리는 중'), ('processing', '받는 중'), ('ready', '준비됨'), ('error', '실패')], default='pending', max_length=12)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('chunks', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SpecChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('kind', models.CharField(default='clause', max_length=8)),
                ('clause', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='tools.specdoc')),
            ],
            options={
                'ordering': ['doc_id', 'order'],
                'indexes': [models.Index(fields=['doc', 'clause'], name='tools_specc_doc_id_8fdb29_idx')],
            },
        ),
    ]
