# Generated by Django 6.0.5 on 2026-10-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_kakaolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('signup', '가입 요청'), ('comment', '댓글'), ('guestbook', '방명록'), ('post', '글'), ('security', '보안')], db_index=True, max_length=20),
        ),
    ]
