# Generated by Django 6.0.5 on 2026-10-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('signup', '가입 요청'), ('comment', '댓글'), ('guestbook', '방명록'), ('post', '글'), ('security', '보안'), ('monitor', '서버 감시')], db_index=True, max_length=20),
        ),
    ]
